version: "1.0"
info:
  model: int-scaffold
packages:
- name: GitSample1Project
  gitServerName: github_com_dharini
  gitUrl: https://github.com/dharini-tech
  gitUsername: dharini-tech
  gitBranch: main
