version: "1.0"
info:
  model: int-scaffold
packages:
- name: GitSample1Project
  gitServerName: github_com_dharini
  gitUrl: https://github.com/dharini-tech
  gitUsername: dharini-tech
  gitBranch: main
services:
- serviceName: project.gitsample1.integrations:SampleDAF2
  packages:
  - name: GitSample1Project
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
